name: interknot
description: "Unified Proxy App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0' # Updated for broader compatibility

dependencies:
  flutter:
    sdk: flutter
  
  # Added for webview functionality
  flutter_inappwebview: ^6.0.0
  
  # Added for date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Using latest stable version

flutter:
  uses-material-design: true

  # Asset declaration for fonts
  assets:
    - assets/fonts/

  # Font family definition
  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/Gilmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilmer-Heavy.ttf
          weight: 900