name: interknot
description: "Unified Proxy App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_inappwebview: ^6.0.0 # For Web Client
  intl: ^0.19.0 # For Date Format
  font_awesome_flutter: ^10.7.0 # For Additional Icons
  shared_preferences: ^2.2.3 # Saving in app


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/Gilmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilmer-Heavy.ttf
          weight: 900